# Generated by Django 4.0.3 on 2022-04-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='card_img',
            field=models.ImageField(blank=True, upload_to='places'),
        ),
    ]
