# Generated by Django 4.0.3 on 2022-04-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
